# config.py - تنظیمات ربات

# توکن ربات تلگرام
BOT_TOKEN = "7844196833:AAFKUNMtUt9ixlp_89757qGXX1_iMaSm75A"

# آیدی عددی سودو (مدیر اصلی ربات)
SUDO_USERS = [5668163693]  # آیدی عددی خودتان را اینجا قرار دهید

# تنظیمات دیتابیس
DATABASE_PATH = "bot_database.db"

# تنظیمات پیش‌فرض گروه
DEFAULT_SETTINGS = {
    "welcome_enabled": True,
    "goodbye_enabled": True,
    "antilink_enabled": False,
    "antispam_enabled": True,
    "antiflood_enabled": True,
    "antiforward_enabled": False,
    "antibot_enabled": False,
    "lock_all": False,
    "lock_media": False,
    "lock_sticker": False,
    "lock_gif": False,
    "lock_voice": False,
    "lock_video": False,
    "lock_document": False,
    "lock_location": False,
    "lock_contact": False,
    "lock_photo": False,
    "lock_poll": False,
    "lock_game": False,
    "lock_inline": False,
    "lock_url": False,
    "lock_forward": False,
    "lock_arabic": False,
    "lock_english": False,
    "lock_emoji": False,
    "slow_mode": 0,
    "max_warn": 3,
    "warn_action": "mute",
    "captcha_enabled": False,
    "captcha_type": "math",
    "night_mode_enabled": False,
    "night_start": "22:00",
    "night_end": "08:00",
    "auto_delete_service": True,
    "max_message_length": 4096,
    "force_join_channel": None,
    "welcome_message": "سلام {mention}! به گروه {group} خوش آمدید! 🎉",
    "goodbye_message": "خداحافظ {user}! امیدواریم دوباره برگردی 👋",
    "rules": "قوانین گروه هنوز تنظیم نشده است.",
    "flood_limit": 5,
    "flood_time": 10,
    "mute_time": 300,
    "ban_time": 0,
    "language": "fa",
}

# لیست بازی‌ها
GAMES = [
    "حدس عدد",
    "حدس کلمه", 
    "دار و درخت",
    "کوییز",
    "مافیا",
    "شرط‌بندی",
    "سنگ کاغذ قیچی",
    "تاس",
    "سکه",
    "معما",
    "چیستان",
    "حقیقت یا جرات",
    "بازی کلمات",
    "ریاضی",
    "حافظه",
    "واکنش سریع",
    "تایپ سریع",
    "emoji quiz",
    "trivia",
    "word chain"
]

# ایموجی‌ها
EMOJIS = {
    "success": "✅",
    "error": "❌", 
    "warning": "⚠️",
    "info": "ℹ️",
    "admin": "👑",
    "user": "👤",
    "group": "👥",
    "settings": "⚙️",
    "lock": "🔒",
    "unlock": "🔓",
    "mute": "🔇",
    "unmute": "🔊",
    "ban": "🚫",
    "warn": "⚡",
    "game": "🎮",
    "music": "🎵",
    "stats": "📊",
    "time": "⏰",
    "calendar": "📅",
    "star": "⭐",
    "fire": "🔥",
    "heart": "❤️",
    "crown": "👑",
    "shield": "🛡️",
    "sword": "⚔️",
    "trophy": "🏆",
    "medal": "🎖️",
    "gift": "🎁",
    "money": "💰",
    "diamond": "💎",
    "rocket": "🚀",
    "robot": "🤖",
    "brain": "🧠",
    "magic": "✨",
    "thunder": "⚡",
    "wave": "👋",
    "party": "🎉",
    "cake": "🎂",
    "flower": "🌸",
    "sun": "☀️",
    "moon": "🌙",
    "rainbow": "🌈",
    "cloud": "☁️",
    "rain": "🌧️",
    "snow": "❄️",
    "leaf": "🍃",
    "tree": "🌳",
    "cat": "🐱",
    "dog": "🐕",
    "bird": "🐦",
    "fish": "🐟",
    "butterfly": "🦋",
    "dice": "🎲",
    "cards": "🃏",
    "target": "🎯",
    "bowling": "🎳",
    "football": "⚽",
    "basketball": "🏀",
    "tennis": "🎾",
    "ping_pong": "🏓",
}

# رتبه‌بندی کاربران بر اساس پیام
RANKS = {
    0: ("🐣 تازه‌کار", 0),
    100: ("🐥 مبتدی", 100),
    500: ("🐤 فعال", 500),
    1000: ("🐔 حرفه‌ای", 1000),
    2500: ("🦅 استاد", 2500),
    5000: ("🦉 افسانه‌ای", 5000),
    10000: ("🦚 نخبه", 10000),
    25000: ("🦋 الماسی", 25000),
    50000: ("🐉 اسطوره", 50000),
    100000: ("👑 خدای گروه", 100000),
}

# متن‌های پیش‌فرض
TEXTS = {
    "fa": {
        "welcome": "سلام {mention}! به گروه {group} خوش آمدید! 🎉",
        "goodbye": "خداحافظ {user}! امیدواریم دوباره برگردی 👋",
        "muted": "🔇 کاربر {user} سکوت شد.\nمدت: {time}",
        "unmuted": "🔊 کاربر {user} از حالت سکوت خارج شد.",
        "banned": "🚫 کاربر {user} مسدود شد.\nدلیل: {reason}",
        "unbanned": "✅ کاربر {user} رفع مسدودیت شد.",
        "warned": "⚡ کاربر {user} اخطار گرفت.\nاخطار {count}/{max}\nدلیل: {reason}",
        "warn_limit": "⚠️ کاربر {user} به حداکثر اخطار رسید و {action} شد.",
        "promoted": "👑 کاربر {user} به ادمین ارتقا یافت.",
        "demoted": "📉 کاربر {user} از ادمینی عزل شد.",
        "no_permission": "❌ شما دسترسی انجام این کار را ندارید.",
        "not_admin": "❌ من ادمین نیستم!",
        "user_not_found": "❌ کاربر یافت نشد.",
        "antilink_triggered": "🔗 لینک شناسایی و حذف شد.",
        "antispam_triggered": "🚫 اسپم شناسایی شد.",
        "antiflood_triggered": "🌊 فلود شناسایی شد. کاربر {user} موقتاً محدود شد.",
        "captcha_required": "🔐 لطفاً کپچا را حل کنید تا بتوانید پیام بفرستید.",
        "captcha_success": "✅ کپچا با موفقیت تأیید شد!",
        "captcha_failed": "❌ کپچا اشتباه بود. لطفاً دوباره تلاش کنید.",
        "settings_saved": "✅ تنظیمات ذخیره شد.",
        "rules_set": "✅ قوانین گروه تنظیم شد.",
        "welcome_set": "✅ پیام خوش‌آمدگویی تنظیم شد.",
        "goodbye_set": "✅ پیام خداحافظی تنظیم شد.",
        "locked": "🔒 {item} قفل شد.",
        "unlocked": "🔓 {item} باز شد.",
        "night_mode_on": "🌙 حالت شب فعال شد.",
        "night_mode_off": "☀️ حالت شب غیرفعال شد.",
        "force_join_set": "✅ کانال اجباری تنظیم شد.",
        "must_join_channel": "⚠️ برای ارسال پیام ابتدا باید در کانال {channel} عضو شوید.",
        "game_started": "🎮 بازی {game} شروع شد!",
        "game_ended": "🏁 بازی پایان یافت!\nبرنده: {winner}",
        "stats_message": "📊 آمار گروه:\n👥 تعداد اعضا: {members}\n📝 تعداد پیام‌ها: {messages}\n👑 تعداد ادمین‌ها: {admins}",
        "user_stats": "📊 آمار کاربر {user}:\n📝 پیام‌ها: {messages}\n⭐ امتیاز: {points}\n🏆 رتبه: {rank}",
        "leaderboard": "🏆 برترین‌های گروه:",
        "help_text": "📚 راهنمای ربات مدیریت گروه\n\nبرای دیدن دستورات از منوی زیر استفاده کنید.",
        "sudo_only": "❌ این دستور فقط برای سودو ربات است.",
        "added_to_group": "✅ ربات به گروه اضافه شد.",
        "removed_from_group": "ربات از گروه حذف شد.",
    },
    "en": {
        "welcome": "Hello {mention}! Welcome to {group}! 🎉",
        "goodbye": "Goodbye {user}! Hope to see you again 👋",
        "muted": "🔇 User {user} has been muted.\nDuration: {time}",
        "unmuted": "🔊 User {user} has been unmuted.",
        "banned": "🚫 User {user} has been banned.\nReason: {reason}",
        "unbanned": "✅ User {user} has been unbanned.",
        "warned": "⚡ User {user} has been warned.\nWarning {count}/{max}\nReason: {reason}",
        "warn_limit": "⚠️ User {user} reached max warnings and has been {action}.",
        "promoted": "👑 User {user} has been promoted to admin.",
        "demoted": "📉 User {user} has been demoted.",
        "no_permission": "❌ You don't have permission to do this.",
        "not_admin": "❌ I'm not an admin!",
        "user_not_found": "❌ User not found.",
        "antilink_triggered": "🔗 Link detected and removed.",
        "antispam_triggered": "🚫 Spam detected.",
        "antiflood_triggered": "🌊 Flood detected. User {user} has been temporarily restricted.",
        "captcha_required": "🔐 Please solve the captcha to send messages.",
        "captcha_success": "✅ Captcha verified successfully!",
        "captcha_failed": "❌ Captcha was wrong. Please try again.",
        "settings_saved": "✅ Settings saved.",
        "rules_set": "✅ Group rules have been set.",
        "welcome_set": "✅ Welcome message has been set.",
        "goodbye_set": "✅ Goodbye message has been set.",
        "locked": "🔒 {item} has been locked.",
        "unlocked": "🔓 {item} has been unlocked.",
        "night_mode_on": "🌙 Night mode enabled.",
        "night_mode_off": "☀️ Night mode disabled.",
        "force_join_set": "✅ Force join channel has been set.",
        "must_join_channel": "⚠️ You must join {channel} to send messages.",
        "game_started": "🎮 Game {game} has started!",
        "game_ended": "🏁 Game ended!\nWinner: {winner}",
        "stats_message": "📊 Group Stats:\n👥 Members: {members}\n📝 Messages: {messages}\n👑 Admins: {admins}",
        "user_stats": "📊 Stats for {user}:\n📝 Messages: {messages}\n⭐ Points: {points}\n🏆 Rank: {rank}",
        "leaderboard": "🏆 Group Leaderboard:",
        "help_text": "📚 Group Management Bot Help\n\nUse the menu below to see commands.",
        "sudo_only": "❌ This command is only for bot sudo.",
        "added_to_group": "✅ Bot has been added to the group.",
        "removed_from_group": "Bot has been removed from the group.",
    }
}
